CSStudyGroup/CardGame

- src/main/resources/static/index.html
> test pull request

- src/main/resources/static/index.html
> merge test

- src/main/resources/static/index.html
> final test

- src/main/resources/static/css/list.css
1. some html apply navibar
2. some css modified
3. navibar margin and z-index modified
4. append controller functions
> html, css, navibar, controller

- src/main/java/com/csStudy/CardGame/domain/Category.java
- src/main/java/com/csStudy/CardGame/dto/CategoryDto.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/resources/application.yml
- src/main/resources/templates/card.html
- src/main/resources/templates/categoryManage.html
- src/main/resources/templates/fragment/head.html
> prevent css, js file caching

- src/main/java/com/csStudy/CardGame/SpringConfigure.java
- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
list.html, category.html, interview.html -> remove title
SpringConfigure.java -> add categoryMapper Bean 
CardController.java -> apply html flow
> controller and etc. commit(22_03_18)

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/js/list.js
- src/main/resources/templates/list.html
CardController -> activate more functions and add, modify AJAX functions
list.html, js -> add AJAX Combo box
> controller and AJAX commit(22_03_18~19)

- src/main/resources/static/css/interview.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
html -> remove cache problem
category -> function implement
interview -> function implement
> front-end pull request(22_03_21)

- src/main/java/com/csStudy/CardGame/repository/CategoryRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/resources/db/migration/V4__add_cnt_trigger.sql
> modify repository

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* category   
-> apply category name
-> modify button event order
* interview  
-> implement finish button and check dialog
* list         
-> remove combobox at view
-> implement update modal
-> implement delete check dialog
* controller
-> change some function's return value  
* service     
-> change function's return value
> html, css, js, controller, service commit(22_03_21)

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/mapper/CardMapperImpl.java
- src/main/resources/static/js/list.js
* Mapper
-> add id setting
* list
-> add update and delete AJAX code
* controller
-> coordinate space
> AJAX commit(22_03_22)

- src/main/java/com/csStudy/CardGame/repository/MariaDBCardRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/resources/templates/card.html
- src/main/resources/templates/fragment/navigator.html
fix repository - MariaDBCategoryRepository
implements click event - card.html
add modal element - navigator.html
> fix repository

- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/head.html
- src/main/resources/templates/fragment/navigator.html
implements insert card feature
> implements insert card feature - navigator

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/mapper/CategoryMapperImpl.java
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
* mapper
-> add category id part
* controller
-> add categoryList to all page's model
-> implement some functions
> mapper, controller, categorymanage request(22_03_23)

- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/head.html
- src/main/resources/templates/fragment/navigator.html
modify navigator - insert/interview feature
modify script loading order - add defer
> modify navigator - insert/interview feature

- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/list.html
* AJAX delete
-> delete categorylist AJAX at list 
-> implement some functions
> AJAX delete, categorymanage request(22_03_23)

- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/navigator.html
> fix minor bug

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/domain/Card.java
- src/main/java/com/csStudy/CardGame/dto/CardDto.java
- src/main/java/com/csStudy/CardGame/mapper/CardMapperImpl.java
- src/main/java/com/csStudy/CardGame/repository/CardRepository.java
- src/main/java/com/csStudy/CardGame/repository/CategoryRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCardRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/db/migration/V6__alter_card_table.sql
- src/main/resources/db/migration/V7__rebuild_cnt_trigger.sql
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/card.html
- src/main/resources/templates/fragment/navigator.html
- src/test/java/com/csStudy/CardGame/repository/MariaDBCardRepositoryTests.java
> modify domain

- src/main/resources/static/css/interview.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* interview, category, list, categorymanage
-> Apply repo changes
* interview, category
-> solve 0 card problem
* interview
-> add title, counter total cards
> Apply repo changes, some functions request(22_03_23)

- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/navigator.html
> implements search feature

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/category.css
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* controller
-> change parameter data type at list mapping function
* list, category, categorymanage, interview
-> apply cursor
* list
-> respond 0 dto
-> change parameters index into id 
-> change some logic
-> implement basic functions
> controller, list, category, categorymanage, interview request(22_03_24)

- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/navigator.html
- src/test/java/com/csStudy/CardGame/CardGameApplicationTests.java
- src/test/java/com/csStudy/CardGame/service/CardGameServiceTests.java
modify interview feature - alert if not check any checkbox or no cards in checked categories
add 6 service function - add/update/delete Cards | add/update/delete Categories
test 6 service function
> modify interview feature / add service function

- build.gradle
- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/list.html
* gradle
-> add JSON dependency
* controller
-> implement category save function
-> pop dialog when try save
-> implement functions so that they do not interfere with each other
-> implement save function
* list
-> rename class and add clickable targets
> gradle, controller, list, categorymanage request(22_03_25)

- src/main/resources/static/css/card.css
- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/card.html
- src/main/resources/templates/fragment/navigator.html
> add cancel button to interview dialog

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/category.css
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* controller
-> add model attributes
* event handler
-> add card added event handler at list, interview, categorymanage, category
* word output
-> deal with word break at list, interview, category
-> modify AJAX queue algorithm
* debug
-> modify categorymanage CSS
> controller, event handler, categorymanage, etc. request(22_03_28)

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/list.js
* controller
-> change AJAX order 
* list
-> modify event handler for tag and question
-> restructure AJAX save algorithm
> controller, list, categorymanage request(22_03_30)

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
* controller
-> add list param and add model attribute
-> modify save button position
-> outer click check
-> add enter event
> controller, categorymanage request(22_03_31)

- src/main/resources/static/js/list.js
- src/main/resources/templates/list.html
* list
-> add keystring
-> rename categoryDto to categoryDtoList
> minor request(22_03_31)

- src/main/java/com/csStudy/CardGame/dto/ChangeCategoryResultDto.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/db/migration/V8__make_cname_not_unique.sql
- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/navigator.html
add dto - ChangeCategoryResultDto
modify navigator.js - add key event | show search keyword
alter category table - drop unique constraint on cname
modify CardGameService - add changeCategories method
> fix swap problem

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
* controller
-> modify changeCategory function
-> height portion border radius
-> always show update target buttons
-> change to object event from window event(keyup)
> controller, categorymanage request(22_04_01)

- src/main/resources/static/css/list.css
- src/main/resources/static/js/interview.js
* interview
-> modify random algorithm
> interview request(22_04_02)

- build.gradle
- src/main/resources/static/css/modal.css
- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/modal.js
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/fragment/head.html
- src/main/resources/templates/fragment/modal.html
- src/main/resources/templates/fragment/navigator.html
> add fragment - modalFragment

- src/main/java/com/csStudy/CardGame/controller/CardController.java
* controller
-> rename card -> cardmain
> minor request(22_04_02)

- src/main/resources/static/js/list.js
- src/main/resources/templates/list.html
* list
-> apply modal fragment
-> remove check section
-> debug error at update card function
> list request(22_04_05)

- src/main/resources/static/css/card.css
- src/main/resources/static/css/cardmain.css
- src/main/resources/templates/cardmain.html
- src/main/resources/templates/fragment/card.html
- src/main/resources/templates/fragment/navigator.html
add fragment - cardFragment
modify fragment - navigator
modify templates - cardmain
> cardFragment implementation

- src/main/resources/static/css/category.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* interview, category
-> renewal UI
* list
-> remove tag
> list, interview, category request(22_04_07)

- src/main/resources/static/css/card_common.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/list.js
- src/main/resources/templates/list.html
* card_common
-> remove padding
* list
-> renewal modal design
> list, card_common request(22_04_08)

- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
> categorymanage request(22_04_09)

- src/main/resources/static/css/card_common.css
- src/main/resources/static/css/category.css
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* add remove default CSS
* remove focus outline
* custom scroll bar
* check mobile and change size
* change dialog to modal
* add slide event handler
* check abnormal update query
> 2022_04_14_request

- src/main/resources/static/css/category.css
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* apply page-title
* remove webkit length
* pack content by main
* modify some design
> 2022_04_15_request

- src/main/resources/static/css/category.css
- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* refactor some files
* fix CSS
> 2022_04_16_request

- src/main/resources/static/css/categorymanage.css
- src/main/resources/static/js/categorymanage.js
- src/main/resources/templates/categorymanage.html
* checking delete category
* checking unload categorymanage without save
> 2022_04_18_request

- src/main/resources/static/css/card_common.css
- src/main/resources/static/css/cardmain.css
- src/main/resources/static/css/navigator.css
- src/main/resources/static/js/card_common.js
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/cardmain.html
- src/main/resources/templates/fragment/navigator.html
- src/main/resources/templates/fragment/selectbox.html
* add custom select box fragment
* add loading page
* apply custom select box to navigator/cardmain
* modify cardmain design
* refactor navigator.js
> 2022_04_20_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/css/card_common.css
- src/main/resources/static/css/category.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/css/list.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/templates/category.html
- src/main/resources/templates/interview.html
- src/main/resources/templates/list.html
* modify default CSS
* modify requestParam controller
* add requestbody some mapping method at controller
* apply combobox
* modify ajax data head to body
* apply markdown at card view
> 2022_04_21_request

- build.gradle
- src/main/java/com/csStudy/CardGame/CacheConfigure.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/templates/fragment/navigator.html
* enable caching - findAllCategories
* fix minor bug
> 2022_04_22_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/domain/Category.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCardRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/application.yml
- src/main/resources/db/migration/V9__alter_tables.sql
- src/main/resources/static/js/card_common.js
- src/main/resources/static/js/cardmain.js
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/cardmain.html
- src/main/resources/templates/categorymanage.html
- src/main/resources/templates/fragment/navigator.html
- src/main/resources/templates/list.html
* add auto_increment V9_alter_tables
* debug repo methods
* inherit Serializable at category entity
* modify deleteCard at service method
* change int(Integer) to String at controller
* modify the overall frontend as dto change
> 2022_04_29_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/dto/CardDto.java
- src/main/java/com/csStudy/CardGame/mapper/CardMapperImpl.java
- src/main/java/com/csStudy/CardGame/repository/CardRepository.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCardRepository.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/resources/static/js/cardmain.js
- src/main/resources/static/js/category.js
- src/main/resources/static/js/categorymanage.js
- src/main/resources/static/js/interview.js
- src/main/resources/static/js/list.js
- src/main/resources/static/js/navigator.js
- src/main/resources/templates/cardmain.html
- src/main/resources/templates/fragment/navigator.html
- src/main/resources/templates/list.html
* modify categoryname to cid at dto
* modify mapper, repo as dto change
* rollback change int(Integer) to String at controller
* change type int(Integer) to Long DTO's cid
* rollback modify the overall frontend as dto change
> 2022_05_02_request

- build.gradle
- src/main/resources/static/css/category.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
* modify design at category, interview
* remove mybatis dependency
> 2022_05_10_request

- src/main/resources/static/css/card_common.css
- src/main/resources/static/css/category.css
- src/main/resources/static/css/interview.css
- src/main/resources/static/js/category.js
- src/main/resources/static/js/interview.js
* add code copy function
* fix minor bug
> 2022_05_11_request

- build.gradle
- src/main/java/com/csStudy/CardGame/SecurityConfigure.java
- src/main/java/com/csStudy/CardGame/WebConfigure.java
- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/resources/static/js/navigator.js
* apply spring security
* add cors test api
> 2022_05_18_request

- src/main/java/com/csStudy/CardGame/SecurityConfigure.java
- src/main/java/com/csStudy/CardGame/controller/MemberController.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBMemberRepository.java
* change login, register restful
* modify passwordEncoder
* add transactional memberRepo
> 2022_05_29_request

- src/main/java/com/csStudy/CardGame/controller/MemberController.java
- src/main/java/com/csStudy/CardGame/dto/SecuredMember.java
- src/main/java/com/csStudy/CardGame/security/JwtAuthenticationFilter.java
- src/main/java/com/csStudy/CardGame/security/JwtTokenProvider.java
> 2022_06_01_request

- src/main/java/com/csStudy/CardGame/SecurityConfigure.java
- src/main/java/com/csStudy/CardGame/controller/CardController.java
> 2022_06_03_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
> 2022_06_04_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/dto/CardDto.java
- src/main/java/com/csStudy/CardGame/mapper/CardMapperImpl.java
- src/main/java/com/csStudy/CardGame/repository/MariaDBCategoryRepository.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
* change category search keyword to category name
* add category name to CardDto
> 2022_06_05_request

- src/main/java/com/csStudy/CardGame/controller/CardController.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
* add some rest api
* modify findCardByCategoryIn function
> 2022_06_07_request

- src/main/java/com/csStudy/CardGame/controller/CardGameController.java
- src/main/java/com/csStudy/CardGame/dto/CardDto.java
- src/main/java/com/csStudy/CardGame/mapper/CardMapperImpl.java
- src/main/java/com/csStudy/CardGame/repository/CategoryRepositoryImpl.java
- src/main/java/com/csStudy/CardGame/security/JwtAuthenticationFilter.java
- src/main/java/com/csStudy/CardGame/service/CardGameService.java
- src/main/java/com/csStudy/CardGame/service/CategoryServiceImpl.java
> 2022_06_18_commit

- src/main/java/com/csStudy/CardGame/advice/CardGameControllerAdvice.java
- src/main/java/com/csStudy/CardGame/domain/Card.java
- src/main/java/com/csStudy/CardGame/domain/CardRequest.java
- src/main/java/com/csStudy/CardGame/domain/Member.java
- src/main/java/com/csStudy/CardGame/domain/OtherRequest.java
- src/main/resources/db/migration/V17__create_sequence.sql
- src/test/java/com/csStudy/CardGame/repository/CardRepositoryTest.java
* apply sequence strategy to all entity
> 2022_07_01_request

- src/main/java/com/csStudy/CardGame/domain/bookmark/entity/Bookmark.java
- src/main/java/com/csStudy/CardGame/domain/member/controller/MemberController.java
- src/main/java/com/csStudy/CardGame/domain/member/service/MemberDetailsService.java
- src/main/java/com/csStudy/CardGame/exception/ApiError.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorEnums.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorException.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorResponse.java
- src/main/java/com/csStudy/CardGame/exception/GlobalExceptionHandler.java
- src/main/java/com/csStudy/CardGame/security/JwtTokenProvider.java
* refactor: custom exception 클래스를 사용한 예외처리 일부 적용
> 2022_09_04_request

- src/main/java/com/csStudy/CardGame/configuration/SecurityConfiguration.java
- src/main/java/com/csStudy/CardGame/configuration/WebConfiguration.java
- src/main/java/com/csStudy/CardGame/domain/card/controller/CardController.java
- src/main/java/com/csStudy/CardGame/domain/card/dto/CardDto.java
- src/main/java/com/csStudy/CardGame/domain/card/entity/Card.java
- src/main/java/com/csStudy/CardGame/domain/card/mapper/CardMapper.java
- src/main/java/com/csStudy/CardGame/domain/card/mapper/CardMapperImpl.java
- src/main/java/com/csStudy/CardGame/domain/card/service/CardServiceImpl.java
- src/main/java/com/csStudy/CardGame/domain/category/controller/CategoryController.java
- src/main/java/com/csStudy/CardGame/domain/category/dto/NewCategoryForm.java
- src/main/java/com/csStudy/CardGame/domain/category/entity/Category.java
- src/main/java/com/csStudy/CardGame/domain/category/mapper/CategoryMapperImpl.java
- src/main/java/com/csStudy/CardGame/domain/category/repository/CategoryRepository.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryService.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryServiceImpl.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorEnums.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorResponse.java
- src/main/java/com/csStudy/CardGame/exception/GlobalExceptionHandler.java
- src/main/java/com/csStudy/CardGame/security/JwtTokenProvider.java
- src/main/resources/db/migration/V1__create_tables.sql
* chore: Category 이름과 Member 닉네임에 UNIQUE 제약 추가
* chore: 허용 method 에 put, delete 추가
* feat: ApiErrorEnums 에 RESOURCE_CONFLICT 에러 추가
* feat: ApiErrorResponse 에 errorReason 추가
* feat: PK, UNIQUE 등의 제약 위배시 예외 처리 코드 추가
* feat: CategoryController 에 addCategory, editCategory api 추가
* feat: @PreAuthorize 로 거부된 요청에 대한 예외처리 추가
* refactor: CategoryController 의 changeCategories api 제거
* fix: jwt 인증필터에서 예외 발생시 요청이 처리되지 않는 문제 수정
> 2022_09_12_request

- src/main/java/com/csStudy/CardGame/domain/category/controller/CategoryController.java
- src/main/java/com/csStudy/CardGame/domain/category/dto/CategoryDtoWithDetail.java
- src/main/java/com/csStudy/CardGame/domain/category/mapper/CategoryMapper.java
- src/main/java/com/csStudy/CardGame/domain/category/mapper/CategoryMapperImpl.java
- src/main/java/com/csStudy/CardGame/domain/category/repository/CategoryRepository.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryService.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryServiceImpl.java
* feat: Category 조회 API 추가 및 pagination 적용
> 2022_09_13_request

- src/main/java/com/csStudy/CardGame/configuration/WebConfiguration.java
- src/main/java/com/csStudy/CardGame/domain/category/controller/CategoryController.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryService.java
- src/main/java/com/csStudy/CardGame/domain/category/service/CategoryServiceImpl.java
- src/main/java/com/csStudy/CardGame/exception/ApiErrorEnums.java
- src/main/java/com/csStudy/CardGame/exception/GlobalExceptionHandler.java
> 2022_09_14_request
